### ISSUE TITLE
eaf安装咨询

### ISSUE THREAD

**Issue by jadestrong** [wineee/nixos-config#1]
https://github.com/wineee/nixos-config/blob/706124bfc47bdc9599b93de285341d32c872a91c/etc/python.nix#L7

`pyqtwebengine` 安装不上，打开注释就会编译失败，咨询下你 `eaf`是怎么装的依赖啊？

**Comment by wineee** [comment]
> https://github.com/wineee/nixos-config/blob/706124bfc47bdc9599b93de285341d32c872a91c/etc/python.nix#L7
> 
> `pyqtwebengine` 安装不上，打开注释就会编译失败，咨询下你 `eaf`是怎么装的依赖啊？

我当时也没有搞定，用的  docker 版的Archlinux （不过重构后 eaf 似乎把 dockerfile 删掉了），后来我转 Arcolinux 了，上周才回来
配置 python 环境的话，这个[视频](https://www.bilibili.com/video/BV1aK4y1V7Fa?from=search&seid=7135837607160085341)可能对你有用, 另外你也可以试试 [mach-nix](https://github.com/DavHau/mach-nix) 这个工具

我这两个月可能没有太多时间折腾，如果你能解决，欢迎分享

**Comment by jadestrong** [comment]
编译失败这个问题我感觉是版本不匹配导致的，我将 `nix-channel` 换成了 `unstable` 那个分支之后再编译就可以通过了。
然后会报一个 `qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""` 的错误，这个是找`plugin`的路径环境变量没有，在 `configuration.nix` 下添加：
```
   environment.variables = {
     QT_QPA_PLATFORM_PLUGIN_PATH = "${pkgs.qt5.qtbase.bin.outPath}/lib/qt-${pkgs.qt5.qtbase.version}/plugins";
   };
```
然后就可以了

**Comment by wineee** [comment]
我尝试用 mach-nix  安装失败： https://github.com/DavHau/mach-nix/issues/321
今天试了试 unstable 的 python 确实可以，应该是 stable 打包有问题没人修。

**Comment by wineee** [comment]
我又遇到了新问题，eaf 的画面不能贴进 emacs 里，报错信息是：
Qt: Session management error: Could not open network socket
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 415, resource id: 36053648, major code: 7 (ReparentWindow), minor code: 0

**Comment by wineee** [comment]
> 编译失败这个问题我感觉是版本不匹配导致的，我将 `nix-channel` 换成了 `unstable` 那个分支之后再编译就可以通过了。 然后会报一个 `qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""` 的错误，这个是找`plugin`的路径环境变量没有，在 `configuration.nix` 下添加：
> 
> ```
>    environment.variables = {
>      QT_QPA_PLATFORM_PLUGIN_PATH = "${pkgs.qt5.qtbase.bin.outPath}/lib/qt-${pkgs.qt5.qtbase.version}/plugins";
>    };
> ```
> 
> 然后就可以了

你是把系统升级到了 unstable 还是仅仅是 python 使用 unstable ？
