### ISSUE TITLE
EXSI部署后进桌面黑屏

### ISSUE THREAD

**Issue by llity** [wineee/nixos-config#2]
KDE都是开启了，输入密码进入桌面就黑屏。还需要配合其他一起配置吗？

谢谢，非常受用。

**Comment by wineee** [comment]
[system](https://github.com/wineee/nixos-config/tree/master/system)/desktop.nix
```
      displayManager = {
        sddm.enable = true;
        defaultSession = "none+xmonad";
      };

```

我同时使用了 xmonad，对应配置 https://github.com/wineee/.dotfiles/blob/master/xmonad/.xmonad/xmonad.hs
如果 xmonad 零配置就是黑屏，你可以删掉 xmonad 相关设置

**Comment by wineee** [comment]
我的配置暂时还没有考虑通用性，如果你要用注意 https://github.com/wineee/nixos-config/blob/master/system/network.nix 里的代理配置，还有 [hardware-configuration.nix](https://github.com/wineee/nixos-config/blob/master/hardware-configuration.nix) ，因为用了 flake 不得不把它加进 git 里

**Comment by llity** [comment]
> [system](https://github.com/wineee/nixos-config/tree/master/system?rgh-link-date=2022-07-17T13%3A10%3A50Z)/desktop.nix
> 
> ```
>       displayManager = {
>         sddm.enable = true;
>         defaultSession = "none+xmonad";
>       };
> ```
> 
> 我同时使用了 xmonad，对应配置 [https://github.com/wineee/.dotfiles/blob/master/xmonad/.xmonad/xmonad.hs](https://github.com/wineee/.dotfiles/blob/master/xmonad/.xmonad/xmonad.hs?rgh-link-date=2022-07-17T13%3A10%3A50Z) 如果 xmonad 零配置就是黑屏，你可以删掉 xmonad 相关设置

暂时注释了，用KDE。我弄了很久软路由，终于安装好了。谢谢

**Comment by llity** [comment]
xmonad 配置文件应该放在哪里呢？

**Comment by wineee** [comment]
> xmonad 配置文件应该放在哪里呢？

https://github.com/wineee/.dotfiles 
https://blog.csdn.net/qq_33831360/article/details/114107985
~/.xmonad/xmonad.hs

**Comment by llity** [comment]
> > xmonad 配置文件应该放在哪里呢？
> 
> [wineee/.dotfiles](https://github.com/wineee/.dotfiles) [blog.csdn.net/qq_33831360/article/details/114107985](https://blog.csdn.net/qq_33831360/article/details/114107985) ~/.xmonad/xmonad.hs

谢谢

**Comment by llity** [comment]
希望增加 nix-container

**Comment by wineee** [comment]
我这个只是个人配置，没有太考虑通用性，你是希望用 nixos-container 干什么
