### ISSUE TITLE
发现V2RAYA运行相关问题

### ISSUE THREAD

**Issue by llity** [wineee/nixos-config#4]
测试发现，v2raya运行有问题，也可能是我自己配置的网络冲突？我用的networking配置的macvlan。

谢谢
<img width="797" alt="image" src="https://user-images.githubusercontent.com/11771112/192953722-0b8a42e9-5399-4dea-beee-ac2127f6f38a.png">

**Comment by wineee** [comment]
你是不是升级到 v2ray 5 了？

**Comment by llity** [comment]
今天用你的配置更新完的。你这个是debug version，应该默认更新最新版？

**Comment by wineee** [comment]
我看了下我这用的 v2ray 4.45.0， nixpkgs 最近刚刚升级了 v2ray 5，用 tag 版 v2raya 确实有问题，需要最新 git 版的 v2raya

**Comment by llity** [comment]
看了一下版本如下，奇怪哦。那应该是v2raya的问题了吧，等更新吗？
```
v2ray-4.45.0
v2ray-domain-list-community-20220808014309
v2ray-geoip-202208040058
```

**Comment by wineee** [comment]
我的还没有出问题，也许是因为 cachix 的构建更新了（https://github.com/wineee/nur-packages/actions）
请再确认一下不是 v2ray 5, 如果用的 4.45 我也不清楚是什么问题

**Comment by wineee** [comment]
我的还没有出问题，也许是因为 cachix 的构建更新了（https://github.com/wineee/nur-packages/actions）
请再确认一下不是 v2ray 5, 如果用的 4.45 我也不清楚是什么问题

**Comment by wineee** [comment]
可以看下日志

**Comment by llity** [comment]
好的，版本都没问题，我再测试一下，谢谢
<img width="900" alt="image" src="https://user-images.githubusercontent.com/11771112/192958969-0ad14ac3-c841-4416-b71c-0b343f6d1f10.png">

**Comment by llity** [comment]
看不出问题

<img width="851" alt="image" src="https://user-images.githubusercontent.com/11771112/192968680-18a1dc6e-e4a2-4e71-a487-81a0f96819cc.png">

**Comment by wineee** [comment]
![image](https://user-images.githubusercontent.com/22803888/192970600-0a3687c8-0de0-49c0-a51c-fca9de94f9f5.png)
看下这个日志

**Comment by llity** [comment]
日志看是v2ray没有运行？

<img width="1294" alt="image" src="https://user-images.githubusercontent.com/11771112/192971974-d93dbbd4-86e9-4e8f-ac3b-de7a7bca2f02.png">

**Comment by wineee** [comment]
修了下 qv2ray 你可以试试
https://github.com/NixOS/nixpkgs/pull/195242

**Comment by llity** [comment]
好的，晚上去测试再反馈

**Comment by wineee** [comment]
https://github.com/NixOS/nixpkgs/pull/204807 现在官方合入v2raya打包了

**Comment by llity** [comment]
已经正常使用。希望能增加 colmena https://github.com/zhaofengli/colmena 部署、clashmeta 网络服务 https://github.com/MetaCubeX/mihomo/blob/Meta/flake.nix 的功能，谢谢。

**Comment by llity** [comment]
好用，谢谢。希望增加sing-box工具

**Comment by wineee** [comment]
> 好用，谢谢。希望增加sing-box工具

这个配置是个人使用的，不是模板，建议fork出来改自己的配置

**Comment by llity** [comment]
已经解决了，谢谢，随时跟着更新
